FROM cloudflare/cloudflared:latest

WORKDIR /app

# 拷贝 tunnel 配置和凭证
COPY tunnel/config.yml /app/config.yml
COPY tunnel/eb890b0f-9acb-4a12-9a06-47eacf65050d.json /app/eb890b0f-9acb-4a12-9a06-47eacf65050d.json
COPY tunnel/.cert.pem /app/.cert.pem

# 启动 cloudflared tunnel
CMD ["tunnel", "--config", "/app/config.yml", "run"]
