/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/exam/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Exam Questions
         * @description 获取入学考试题目
         */
        get: operations["get_exam_questions_api_exam_questions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Exam */
        post: operations["submit_exam_api_exam_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assign_major": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Major */
        post: operations["assign_major_api_assign_major_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admission_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admission Info
         * @description 获取当前用户的用户名和分配专业（tier）。需前端携带 Authorization: Bearer <token>
         */
        get: operations["get_admission_info_api_admission_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exam/quick_login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Quick Login */
        post: operations["quick_login_api_exam_quick_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game Config
         * @description 获取游戏配置（供前端使用）
         */
        get: operations["get_game_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdmissionInfoResponse */
        AdmissionInfoResponse: {
            /** Username */
            username: string;
            /** Assigned Major */
            assigned_major: string;
            /** Token */
            token: string;
        };
        /** AssignMajorRequest */
        AssignMajorRequest: {
            /** Token */
            token: string;
        };
        /** AssignMajorResponse */
        AssignMajorResponse: {
            /** Success */
            success: boolean;
            /** Major */
            major: string;
            /** Major Abbr */
            major_abbr: string;
            /** Courses */
            courses: {
                [key: string]: string;
            }[];
        };
        /** ExamQuestion */
        ExamQuestion: {
            /** Id */
            id: string;
            /** Content */
            content: string;
            /** Score */
            score: number;
            /** Options */
            options?: string[] | null;
        };
        /** ExamResponse */
        ExamResponse: {
            /** Status */
            status: string;
            /** Score */
            score?: number;
            /** Tier */
            tier?: string;
            /** Token */
            token?: string;
            /** Message */
            message?: string;
        };
        /** ExamSubmission */
        ExamSubmission: {
            /** Username */
            username: string;
            /** Answers */
            answers: {
                [key: string]: string;
            };
            /** Token */
            token?: string;
            /** Custom Llm Model */
            custom_llm_model?: string | null;
            /** Custom Llm Api Key */
            custom_llm_api_key?: string | null;
            /** Custom Llm Provider */
            custom_llm_provider?: string | null;
        };
        /** GameConfigResponse */
        GameConfigResponse: {
            /** Version */
            version: string;
            semester: components["schemas"]["SemesterConfigResponse"];
            /** Course States */
            course_states: {
                [key: string]: {
                    [key: string]: string;
                };
            };
            /** Cooldowns */
            cooldowns: {
                [key: string]: number;
            };
            /** Tick Interval */
            tick_interval: number;
            /** Base Drain */
            base_drain: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** QuickLoginRequest */
        QuickLoginRequest: {
            /** Username */
            username: string;
            /** Token */
            token?: string;
            /** Custom Llm Model */
            custom_llm_model?: string | null;
            /** Custom Llm Api Key */
            custom_llm_api_key?: string | null;
            /** Custom Llm Provider */
            custom_llm_provider?: string | null;
        };
        /** QuickLoginResponse */
        QuickLoginResponse: {
            /** Status */
            status: string;
            /** Token */
            token?: string | null;
            /** Username */
            username?: string | null;
            /** Assigned Major */
            assigned_major?: string | null;
            /** Message */
            message?: string | null;
        };
        /** SemesterConfigResponse */
        SemesterConfigResponse: {
            /** Durations */
            durations: {
                [key: string]: number;
            };
            /** Default Duration */
            default_duration: number;
            /** Speed Modes */
            speed_modes: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_exam_questions_api_exam_questions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamQuestion"][];
                };
            };
        };
    };
    submit_exam_api_exam_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_major_api_assign_major_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignMajorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignMajorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_admission_info_api_admission_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdmissionInfoResponse"];
                };
            };
        };
    };
    quick_login_api_exam_quick_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickLoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameConfigResponse"];
                };
            };
        };
    };
}
